version: '3.4'

services:
  newavalon.app:
    image: ${DOCKER_REGISTRY-}newavalonapp
    container_name: avalon_app
    build:
      context: .
      dockerfile: NewAvalon.App/Dockerfile
    ports:
      - 10143:443
      - 10180:80
    #networks:
    #  - new-avalon_network
    #depends_on:
    #  - newavalon.mq

networks:
  new-avalon_network:

#  newavalon.mq:
#    image: rabbitmq:3.8.14-management
#    container_name: new-avalon_mq
#    hostname: new-avalon_queue
#    volumes:
#        - ./Queue/data/:/var/lib/rabbitmq
#        - ./Queue/log/:/var/log/rabbitmq
#    environment:
#        RABBITMQ_DEFAULT_USER: guest
#        RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - new-avalon_network